database-settings:
  enabled: false
  type: "mysql" # change to 'sqlite' for SQLite
  database: "playtimes"
  host: "localhost"
  port: 3306
  user: "root"
  password: "password"
  useSSL: false
  # IMPORTANT:
  # 'serverId' must be UNIQUE to the server!
  # If you have multiple servers running PlayTimes make sure each config has a unique 'serverId'
  # The 'serverId' will also be used for the placeholders, %PlayTimes_db_serverId% for example: %PlayTimes_db_survival%
  # The placeholder will return the time played in that server.
  serverId: "survival"

# If enabled, upon starting your server if will purge all user info that is older than x months.
# NOTE: this will only purge data for the specific serverId. Not data for all servers!
purge-database:
  enabled: false
  months: 12
